### ISSUE TITLE
Problem: C4Social should have a motivating rallying cry

### ISSUE THREAD

**Issue by LEDCoyote** [c4social/C4-tools#12]
### Problem
In getting up to speed on the C4 process, its rationale, and etc., I read Hintjen's "The ZeroMQ Community", and the section [Crazy, Beautiful, and Easy](https://zguide.zeromq.org/docs/chapter6/#Crazy-Beautiful-and-Easy) identifies a problem that free software projects can have. Namely, they need "a goal that’s crazy and simple enough to get people out of bed in the morning," as a motivating rallying cry for the community.

It's an actual problem, because without a strong brand C4 projects will have a harder time getting developers excited to contribute.

It is valuable to solve because the larger and more diverse the community we attract, the more accurate will be the issues we address and the better will be our solutions.

### Proposed Solution
I thought about this for awhile, and what I came up with for C4Social is
> ### "Evolving the Fediverse at the Speed of Community"

- _Evolving:_ Evolution is required for systems and communities to survive and thrive for the long term. This is principally motivating since it's a frequent complaint among federated web (Fediverse) users that their feature requests get stomped down or ignored. "Innovating" could easily substitute here.
- _the Fediverse:_ We aren't focused on just one application. The processes and community built here are applicable to any federated ActivityPub (or other) application. Is this the best word, as "Fediverse" is mostly unknown outside the community?
- _Speed:_ People like fast. If they ask for a valuable feature they don't want to wait forever for it. If they contribute a patch they don't want it to languish and die without being merged.
- _Community:_ This is what it's all about 😉 A valid question here is, "is the community fast or slow?" I come down on the side of fast. Nothing is faster at identifying needs than a widespread community of users. And if the ethos of open source is a bias toward action and creating solutions, then nothing can be faster than the community solving its own problems, _as long as_ the contribution process isn't a hindrance, which C4 seeks to prevent.

Update (2021-08-22): Added to the community section.

**Comment by aschrijver** [comment]
I like your slogan, but I feel that Community overall is not perceive as fast. Many people associate with the slow process of having to seek community consensus before anything goes. E.g. maintainers that chose a BDFL model like the fact that they can overrule any community discussion.

As you know the SocialHub is all about Evolving the Fediverse, and it is a prime example where many federated devs ignore the community to just do their own thing, ignorant of a win-win and that participation is for their own self-interest as well. Of course good organization and processes matter, so a community could be fast too, I agree.

Also I don't know if "speed" is the proper word in a Fediverse context either. In the culture many fedizens are happy with 'slow and healthy growth' too, and speed refers more to the outside world of disruption and 'move fast and break things'.

An alternative:

> ### "C4Social: Empowering Healthy Community for a Healthy Fediverse"

**Comment by weex** [comment]
The current thing on the website and posted in various places is:

**"We are creating magic through evolution of the Fediverse!"**

So channeling my inner lawyer on C4, I would encourage discussion here to focus on what's wrong with that slogan first and if it's valuable enough to solve that it should be a focus. I'd argue the main value is in building consensus around a mission, content aside.

If it's a valid problem, perhaps some of these terms that I considered on the way to that slogan can help brainstorming
* experiences
* exponential
* human-powered
* evolutionary
* collective intelligence
* discovery
* positivity
* empowering wizardry

**Comment by LEDCoyote** [comment]
Oop, sorry @weex , I have indeed seen you write that in various places but thought it was a personal slogan. I think it's good, though maybe a little vague though as to what is about?

"Creating magic" is a lovely and evocative phrasing. It would be nice to keep it in somehow.

"Evolution of the Fediverse" I think is also great, and is centered in my initial thoughts.

@aschrijver brings up some excellent points. "Healthy" > "Fast" is a good one. A key bit that I like from his suggestion is "Empowerment," which I think is really at the crux of C4.

**Comment by LEDCoyote** [comment]
As to whether it's a valid problem, having a slogan is better than not having one, and it doesn't have to be perfect. I opened it on the incorrect perception that there wasn't a slogan yet.

I could probably close this issue on those grounds, though I can leave it open if folks would like to continue the discussion.

**Comment by LEDCoyote** [comment]
Well, actually I will close this. The problem stated is not a real one, since the slogan does exist, and it is a good one. Can open a different issue if we want to keep workshopping the wording.
